<?php

// Theme Definitions
// Each theme defines its own set of CSS variables or direct style values

$themes = [
    'Halloween Theme' => [
        '--primary-background' => '#2C0F42', // Deep Purple
        '--secondary-background' => '#4B1D6B', // Darker Purple
        '--tertiary-background' => '#6A2C9B', // Medium Purple
        '--accent-color-1' => '#FF6600',    // Bright Orange
        '--accent-color-2' => '#CCFF00',    // Lime Green
        '--text-light' => '#F0F0F0',        // Off-white
        '--text-dark' => '#D4D4D4',         // Lighter gray
        '--button-shadow-color' => 'rgba(255, 102, 0, 0.3)',
        '--button-hover-shadow-color' => 'rgba(255, 102, 0, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.3)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.2)',
        '--cta-shadow-color' => 'rgba(255, 102, 0, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(255, 102, 0, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(255, 102, 0, 0.4)',
        '--card-background' => '#212529', // Dark for cards
        '--card-text-color' => '#F8F9FA', // Light for card text
        '--card-accent-color' => '#FFC107', // Yellow for card titles
        '--hr-color' => 'rgba(255, 102, 0, 0.5)',
        '--swal-popup-bg' => '#4B1D6B',
        '--swal-border-color' => '#FF6600',
        '--swal-title-color' => '#FF6600',
        '--swal-text-color' => '#F0F0F0',
        '--swal-button-bg' => '#FF6600',
        '--swal-button-hover-bg' => '#E65C00',
        // Specific for particles.js
        'particle-color' => '#FF6600',
        'particle-line-color' => '#CCFF00',
    ],
    'Winter Wonderland' => [
        '--primary-background' => '#E0F2F7', // Light Blue/White
        '--secondary-background' => '#B3E5FC', // Sky Blue
        '--tertiary-background' => '#81D4FA', // Light Blue
        '--accent-color-1' => '#2196F3',    // Blue
        '--accent-color-2' => '#00BCD4',    // Cyan
        '--text-light' => '#263238',        // Dark Grey
        '--text-dark' => '#455A64',         // Medium Grey
        '--button-shadow-color' => 'rgba(33, 150, 243, 0.3)',
        '--button-hover-shadow-color' => 'rgba(33, 150, 243, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.1)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.05)',
        '--cta-shadow-color' => 'rgba(33, 150, 243, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(33, 150, 243, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(33, 150, 243, 0.4)',
        '--card-background' => '#FFFFFF',
        '--card-text-color' => '#263238',
        '--card-accent-color' => '#2196F3',
        '--hr-color' => 'rgba(33, 150, 243, 0.5)',
        '--swal-popup-bg' => '#B3E5FC',
        '--swal-border-color' => '#2196F3',
        '--swal-title-color' => '#2196F3',
        '--swal-text-color' => '#263238',
        '--swal-button-bg' => '#2196F3',
        '--swal-button-hover-bg' => '#1976D2',
        // Specific for particles.js
        'particle-color' => '#FFFFFF',
        'particle-line-color' => '#BBDEFB',
    ],
    'Botanical/Nature Theme' => [
        '--primary-background' => '#2E8B57', // Sea Green
        '--secondary-background' => '#3CB371', // Medium Sea Green
        '--tertiary-background' => '#66CDAA', // Medium Aquamarine
        '--accent-color-1' => '#FFD700',    // Gold
        '--accent-color-2' => '#A2B19F',    // Muted Green-Grey for subtle accents
        '--text-light' => '#F5F5DC',        // Beige
        '--text-dark' => '#D4D4D4',         // Light Grey
        '--button-shadow-color' => 'rgba(255, 215, 0, 0.3)',
        '--button-hover-shadow-color' => 'rgba(255, 215, 0, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.3)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.2)',
        '--cta-shadow-color' => 'rgba(255, 215, 0, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(255, 215, 0, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(255, 215, 0, 0.4)',
        '--card-background' => '#3D9970', // Slightly darker green for cards
        '--card-text-color' => '#F5F5DC',
        '--card-accent-color' => '#FFD700',
        '--hr-color' => 'rgba(255, 215, 0, 0.5)',
        '--swal-popup-bg' => '#3CB371',
        '--swal-border-color' => '#FFD700',
        '--swal-title-color' => '#FFD700',
        '--swal-text-color' => '#F5F5DC',
        '--swal-button-bg' => '#FFD700',
        '--swal-button-hover-bg' => '#CCAC00',
        // Specific for particles.js
        'particle-color' => '#F5F5DC',
        'particle-line-color' => '#A2B19F',
    ],
    'Dark Mode Minimalist' => [
        '--primary-background' => '#1A1A1A', // Very Dark Grey
        '--secondary-background' => '#2C2C2C', // Darker Grey
        '--tertiary-background' => '#3F3F3F', // Medium Grey
        '--accent-color-1' => '#00BCD4',    // Cyan
        '--accent-color-2' => '#B0BEC5',    // Light Grey-Blue
        '--text-light' => '#E0E0E0',        // Light Grey
        '--text-dark' => '#9E9E9E',         // Muted Grey
        '--button-shadow-color' => 'rgba(0, 188, 212, 0.3)',
        '--button-hover-shadow-color' => 'rgba(0, 188, 212, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.5)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.4)',
        '--cta-shadow-color' => 'rgba(0, 188, 212, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(0, 188, 212, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(0, 188, 212, 0.4)',
        '--card-background' => '#212121',
        '--card-text-color' => '#E0E0E0',
        '--card-accent-color' => '#00BCD4',
        '--hr-color' => 'rgba(0, 188, 212, 0.5)',
        '--swal-popup-bg' => '#2C2C2C',
        '--swal-border-color' => '#00BCD4',
        '--swal-title-color' => '#00BCD4',
        '--swal-text-color' => '#E0E0E0',
        '--swal-button-bg' => '#00BCD4',
        '--swal-button-hover-bg' => '#0097A7',
        // Specific for particles.js
        'particle-color' => '#E0E0E0',
        'particle-line-color' => '#9E9E9E',
    ],
    'Sunset Gradient' => [
        '--primary-background' => '#FF7043', // Deep Orange
        '--secondary-background' => '#FFAB91', // Light Orange
        '--tertiary-background' => '#FFCCBC', // Lighter Orange
        '--accent-color-1' => '#FFEB3B',    // Yellow
        '--accent-color-2' => '#E91E63',    // Pink
        '--text-light' => '#FFFFFF',        // White
        '--text-dark' => '#FFE0B2',         // Very Light Orange
        '--button-shadow-color' => 'rgba(255, 235, 59, 0.3)',
        '--button-hover-shadow-color' => 'rgba(255, 235, 59, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.2)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.1)',
        '--cta-shadow-color' => 'rgba(255, 235, 59, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(255, 235, 59, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(255, 235, 59, 0.4)',
        '--card-background' => '#FF8A65',
        '--card-text-color' => '#FFFFFF',
        '--card-accent-color' => '#FFEB3B',
        '--hr-color' => 'rgba(255, 235, 59, 0.5)',
        '--swal-popup-bg' => '#FFAB91',
        '--swal-border-color' => '#FFEB3B',
        '--swal-title-color' => '#FFEB3B',
        '--swal-text-color' => '#FFFFFF',
        '--swal-button-bg' => '#FFEB3B',
        '--swal-button-hover-bg' => '#FDD835',
        // Specific for particles.js
        'particle-color' => '#FFFFFF',
        'particle-line-color' => '#FFE0B2',
    ],
    'Retro/Vaporwave' => [
        '--primary-background' => '#2E0854', // Dark Purple
        '--secondary-background' => '#4C0A78', // Medium Purple
        '--tertiary-background' => '#6A0CA9', // Light Purple
        '--accent-color-1' => '#00FFFF',    // Cyan
        '--accent-color-2' => '#FF00FF',    // Magenta
        '--text-light' => '#FFFAFA',        // Snow White
        '--text-dark' => '#E0BBE4',         // Pastel Purple
        '--button-shadow-color' => 'rgba(0, 255, 255, 0.3)',
        '--button-hover-shadow-color' => 'rgba(0, 255, 255, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.4)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.3)',
        '--cta-shadow-color' => 'rgba(0, 255, 255, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(0, 255, 255, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(0, 255, 255, 0.4)',
        '--card-background' => '#3A066F',
        '--card-text-color' => '#FFFAFA',
        '--card-accent-color' => '#FF00FF',
        '--hr-color' => 'rgba(0, 255, 255, 0.5)',
        '--swal-popup-bg' => '#4C0A78',
        '--swal-border-color' => '#00FFFF',
        '--swal-title-color' => '#00FFFF',
        '--swal-text-color' => '#FFFAFA',
        '--swal-button-bg' => '#00FFFF',
        '--swal-button-hover-bg' => '#00CCCC',
        // Specific for particles.js
        'particle-color' => '#00FFFF',
        'particle-line-color' => '#FF00FF',
    ],
    'Candy Pop / Pastel Sweet' => [
        '--primary-background' => '#FFEBEE', // Light Pink
        '--secondary-background' => '#F8BBD0', // Pastel Pink
        '--tertiary-background' => '#F48FB1', // Medium Pink
        '--accent-color-1' => '#8BC34A',    // Light Green
        '--accent-color-2' => '#FFC107',    // Amber
        '--text-light' => '#424242',        // Dark Grey
        '--text-dark' => '#616161',         // Medium Dark Grey
        '--button-shadow-color' => 'rgba(139, 195, 74, 0.3)',
        '--button-hover-shadow-color' => 'rgba(139, 195, 74, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.1)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.05)',
        '--cta-shadow-color' => 'rgba(139, 195, 74, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(139, 195, 74, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(139, 195, 74, 0.4)',
        '--card-background' => '#FFCDD2',
        '--card-text-color' => '#424242',
        '--card-accent-color' => '#8BC34A',
        '--hr-color' => 'rgba(139, 195, 74, 0.5)',
        '--swal-popup-bg' => '#F8BBD0',
        '--swal-border-color' => '#8BC34A',
        '--swal-title-color' => '#8BC34A',
        '--swal-text-color' => '#424242',
        '--swal-button-bg' => '#8BC34A',
        '--swal-button-hover-bg' => '#689F38',
        // Specific for particles.js
        'particle-color' => '#F8BBD0',
        'particle-line-color' => '#FFC107',
    ],
    'Cyberpunk Theme' => [
        '--primary-background' => '#0D0D0D', // Very Dark Grey
        '--secondary-background' => '#1A1A1A', // Dark Grey
        '--tertiary-background' => '#2A2A2A', // Medium Dark Grey
        '--accent-color-1' => '#00FFFF',    // Neon Cyan
        '--accent-color-2' => '#FF00FF',    // Neon Magenta
        '--text-light' => '#00FF00',        // Neon Green
        '--text-dark' => '#00BFFF',         // Deep Sky Blue
        '--button-shadow-color' => 'rgba(0, 255, 255, 0.5)',
        '--button-hover-shadow-color' => 'rgba(0, 255, 255, 0.8)',
        '--navbar-shadow-color' => 'rgba(0, 255, 255, 0.5)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.7)',
        '--cta-shadow-color' => 'rgba(0, 255, 255, 0.6)',
        '--cta-hover-shadow-color' => 'rgba(0, 255, 255, 0.9)',
        '--back-to-top-shadow-color' => 'rgba(0, 255, 255, 0.5)',
        '--card-background' => '#1A1A1A',
        '--card-text-color' => '#00FF00',
        '--card-accent-color' => '#FF00FF',
        '--hr-color' => 'rgba(0, 255, 255, 0.8)',
        '--swal-popup-bg' => '#1A1A1A',
        '--swal-border-color' => '#00FFFF',
        '--swal-title-color' => '#00FFFF',
        '--swal-text-color' => '#00FF00',
        '--swal-button-bg' => '#FF00FF',
        '--swal-button-hover-bg' => '#CC00CC',
        // Specific for particles.js
        'particle-color' => '#00FFFF',
        'particle-line-color' => '#FF00FF',
    ],
    'Japanese Zen' => [
        '--primary-background' => '#F5F5DC', // Beige
        '--secondary-background' => '#E0E0B8', // Light Khaki
        '--tertiary-background' => '#C8C8A9', // Medium Khaki
        '--accent-color-1' => '#8B4513',    // Saddle Brown
        '--accent-color-2' => '#5F9EA0',    // Cadet Blue
        '--text-light' => '#36454F',        // Charcoal
        '--text-dark' => '#556B2F',         // Dark Olive Green
        '--button-shadow-color' => 'rgba(139, 69, 19, 0.3)',
        '--button-hover-shadow-color' => 'rgba(139, 69, 19, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.1)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.05)',
        '--cta-shadow-color' => 'rgba(139, 69, 19, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(139, 69, 19, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(139, 69, 19, 0.4)',
        '--card-background' => '#F0F0D8',
        '--card-text-color' => '#36454F',
        '--card-accent-color' => '#8B4513',
        '--hr-color' => 'rgba(139, 69, 19, 0.5)',
        '--swal-popup-bg' => '#E0E0B8',
        '--swal-border-color' => '#8B4513',
        '--swal-title-color' => '#8B4513',
        '--swal-text-color' => '#36454F',
        '--swal-button-bg' => '#8B4513',
        '--swal-button-hover-bg' => '#6F380A',
        // Specific for particles.js
        'particle-color' => '#36454F',
        'particle-line-color' => '#5F9EA0',
    ],
    'Dreamy Galaxy' => [
        '--primary-background' => '#191970', // Midnight Blue
        '--secondary-background' => '#483D8B', // Dark Slate Blue
        '--tertiary-background' => '#6A5ACD', // Slate Blue
        '--accent-color-1' => '#9370DB',    // Medium Purple
        '--accent-color-2' => '#87CEEB',    // Sky Blue
        '--text-light' => '#E6E6FA',        // Lavender Blush
        '--text-dark' => '#D8BFD8',         // Thistle
        '--button-shadow-color' => 'rgba(147, 112, 219, 0.3)',
        '--button-hover-shadow-color' => 'rgba(147, 112, 219, 0.5)',
        '--navbar-shadow-color' => 'rgba(0, 0, 0, 0.4)',
        '--section-shadow-color' => 'rgba(0, 0, 0, 0.3)',
        '--cta-shadow-color' => 'rgba(147, 112, 219, 0.4)',
        '--cta-hover-shadow-color' => 'rgba(147, 112, 219, 0.6)',
        '--back-to-top-shadow-color' => 'rgba(147, 112, 219, 0.4)',
        '--card-background' => '#2F2F6F',
        '--card-text-color' => '#E6E6FA',
        '--card-accent-color' => '#9370DB',
        '--hr-color' => 'rgba(147, 112, 219, 0.5)',
        '--swal-popup-bg' => '#483D8B',
        '--swal-border-color' => '#9370DB',
        '--swal-title-color' => '#9370DB',
        '--swal-text-color' => '#E6E6FA',
        '--swal-button-bg' => '#9370DB',
        '--swal-button-hover-bg' => '#7A4EB6',
        // Specific for particles.js
        'particle-color' => '#E6E6FA',
        'particle-line-color' => '#87CEEB',
    ],
];

?>